- name: Set up McMyAdmin
  hosts: all

 - name: Create McMyAdmin Container
    docker_container:
      name: McMyAdmin
      image: "linuxserver/mcmyadmin2"
      restart_policy: always
      published_ports:
        - 8080:8080
        - 25565:25565
      volumes:
        - /opt/minecraft:/minecraft
        - /etc/localtime:/etc/localtime:ro
      env:
        SONARQUBE_JDBC_USERNAME: "{{ sonar_rds_username }}"
        SONARQUBE_JDBC_PASSWORD: "{{ sonar_rds_password }}"
        SONARQUBE_JDBC_URL: "jdbc:postgresql://{{ sonar_rds_endpoint }}/sonar"
        VIRTUAL_HOST: "{{ sonar_virtual_host }}"
        VIRTUAL_PORT: 9000
      networks:
        - name: backend
          ipv4_address: 192.168.42.42